### ISSUE TITLE
mpg123: no process found

### ISSUE THREAD

**Issue by Koala** [dewomser/Webradio-Bash-Dialog#2]
Fehlermeldung in der Console:
> mpg123: no process found

Ausgabe in der fifo.txt:

> mpg123: unrecognized option '--utf8'
> mpg123: unrecognized option '--title'
> mpg123: unrecognized option '--preload'
> mpg123: unrecognized option '--smooth'
> Cannot initialize semaphores: File exists

Auch wenn ich diese Optionen beim Aufruf weg lasse, funktioniert es nicht und es erscheint obige Fehlermeldung.

$ mpg123 -V
> mpg321 version 0.3.2. Copyright (C) 2001, 2002 Joe Drew,

**Comment by dewomser** [comment]
"mpg123: no process found"  Meldung ist jetzt weg. 
--
mpg123 --version
mpg123 1.25.13
---
Bei mir läuft das Radio wunderbar .  Wahrscheinlich  ist Deine mpg123 Version veraltet.

**Comment by Koala** [comment]
Bei mir ist nur mpg321 installiert und es befindet sich ein Link in /etc/alternatives/mpg123 der auf /usr/bin/mpg321
Und es gibt einen Link /usr/bin/mpg123 der auf /etc/alternatives/mpg123 verweist.
Es bedarf also einer Prüfung, ob /etc/alternatives/mpg123 auf /usr/bin/mpg123.bin verweist. Nur dann wird auch das richtige Programm gestartet und das Script funktioniert.

Verwendetes System: Debian 10

**Comment by dewomser** [comment]
probier mal upzudaten , dann wird es funktionieren
Hier  Kubuntu 20.04.1
